### ISSUE TITLE
Incorrect build configuration.

### ISSUE THREAD

**Issue by KevlarBandit** [Fabricators-of-Create/create-fabric-addon-template#4]
No Indium is listed as 1.0.1+1.18.2 but the correct version is actually 1.0.2+1.18.2 as per https://github.com/Luligabi1/NoIndium/blob/1.18.2/gradle.properties
Further, the maven for No Indium is: url = 'https://maven.cafeteria.dev/releases/'
Instead of: url = 'https://maven.cafeteria.dev/'

Making this change will also fix the dependency error with fake player api.

**Comment by TropheusJ** [comment]
a lot has been changed and this is no longer an issue
